/**
 * Smart Container Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.4.1-SNAPSHOT
 * Contact: i.bileychik@itransition.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Metadata {
    startTime?: number;
    duration?: number;
}
